basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# TEMPLATE URLS!
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # to je zato što default User model koje importamo ima već svoja polja - ovo služi da ta polja extendamo s nekim svojim specifičnim
    # one to one je field relationship

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

# dodatni moduli za autentifikaciju
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else: 
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered,
                                                        })


# LOGIN funkcije

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to log in and failed!")
            print("username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details")

    else:
        return render(request,'basic_app/login.html',{})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Base</title>

</head>

    <nav class="navbar navbar-light bg-success">


            <a class="navbar-brand" href="#">
            <img src="#" width="30" height="30" class="d-inline-block align-top" alt="">
            APP BRAND
            </a>

            <!-- <div class="collapse navbar-collapse" id="navbarNav"> -->

                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">         
                    
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}">DJANGO <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li>
                            <a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="navbar-link" href="{% url 'basic_app:user_login' %}">LOGIN</a>
                        </li>
                    {% endif %}

                </ul>

            <!-- </div> -->

                <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
        <!-- </div> -->
    </nav>


    

    <div>
    {% block body_block %}
    {% endblock %}
    </div>

    
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>


{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Log in</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

templates/basic_app/registration.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>

    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the Form</h3>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" id="" value="Register">
    </form>

    {% endif %}

</div>

{% endblock %}